// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using XlightsQueue.Data;

#nullable disable

namespace XlightsQueue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404180000_AddStripePublishableKey")]
    partial class AddStripePublishableKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
