// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XlightsQueue.Data;

#nullable disable

namespace XlightsQueue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("XlightsQueue.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("XlightsQueue.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FppPlaylistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FppPlaylistName = "HolidayFavorites",
                            IsEnabled = true,
                            Name = "Holiday Favorites"
                        });
                });

            modelBuilder.Entity("XlightsQueue.Models.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("SongId");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("XlightsQueue.Models.ShowConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPlayDefault")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BumpCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonateCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPlaylistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FmRadioStation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FppAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FppPollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InterruptForUserSongs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSongsPerWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MqttBrokerHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MqttBrokerPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MqttEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MqttPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MqttTopicPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MqttUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RateLimitWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowScheduleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialMediaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SongRequestCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShowConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoPlayDefault = true,
                            BumpCost = 1.00m,
                            DefaultPlaylistName = "",
                            DefaultTheme = "dark",
                            DonateCost = 5.00m,
                            FmRadioStation = "",
                            FppAddress = "192.168.1.100",
                            FppPollingIntervalSeconds = 5,
                            InterruptForUserSongs = true,
                            MaxSongsPerWindow = 3,
                            MqttBrokerHost = "",
                            MqttBrokerPort = 1883,
                            MqttEnabled = false,
                            MqttPassword = "",
                            MqttTopicPrefix = "xlights",
                            MqttUsername = "",
                            RateLimitWindowMinutes = 60,
                            ShowScheduleJson = "[]",
                            SiteName = "Queue The Magic",
                            SocialMediaJson = "[]",
                            SongRequestCost = 1.00m
                        });
                });

            modelBuilder.Entity("XlightsQueue.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("XlightsQueue.Models.SongRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "SessionToken")
                        .IsUnique();

                    b.ToTable("SongRatings");
                });

            modelBuilder.Entity("XlightsQueue.Models.ThankYou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ThankYous");
                });

            modelBuilder.Entity("XlightsQueue.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("XlightsQueue.Models.QueueItem", b =>
                {
                    b.HasOne("XlightsQueue.Models.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId");

                    b.HasOne("XlightsQueue.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("XlightsQueue.Models.Song", b =>
                {
                    b.HasOne("XlightsQueue.Models.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("XlightsQueue.Models.SongRating", b =>
                {
                    b.HasOne("XlightsQueue.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("XlightsQueue.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
